"""2-category Para's 1-cell algebra — the data layer.

A 1-cell of Para is a parametric morphism between sorts. The algebra of
1-cells is generated by these primitives:

    eq(name)                   — atomic V-enriched 1-cell (declared Equation)
    lit(term)                  — 0-ary constant morphism (1 → A)
    seq(f, g)                  — sequential composition  (f ; g)
    par(f, g)                  — monoidal product        (f ⊗ g)
    copy(sort)                 — comonoid copy           (Δ_A : A → A × A)
    delete(sort)               — comonoid delete         (!_A : A → 1)
    algebra_hom(F, dir, cells) — induced (co)algebra hom over polynomial F
    lens(fwd, bwd[, residual]) — Optic 1-cell (height-1 or height-2)

A Cell is a Hydra union ``ua.para.Cell``. This module hosts the data
types, constructors, accessors, and pretty-printer. The interpreter
(``compile_cell``, ``CompiledLens``) lives in ``_para_runtime``; the
algebra-hom walker lives in ``_para_alg_hom``. Public symbols are
re-exported from this module for stable import paths.
"""
from __future__ import annotations

import hydra.dsl.terms as Terms
from hydra.core import Field, Name

from unialg.assembly.functor import Functor
from unialg.algebra.sort import Sort, ProductSort, sort_wrap
from unialg.terms import _RecordView, _literal_value


# ---------------------------------------------------------------------------
# Type & variant names
# ---------------------------------------------------------------------------

CELL_TYPE_NAME = Name("ua.para.Cell")

_K_EQ          = Name("eq")
_K_LIT         = Name("lit")
_K_IDEN        = Name("iden")
_K_SEQ         = Name("seq")
_K_PAR         = Name("par")
_K_COPY        = Name("copy")
_K_DELETE      = Name("delete")
_K_ALG_HOM     = Name("algebraHom")
_K_LENS        = Name("lens")

# Sub-record type for the algebra_hom payload (3 fields).
_ALG_HOM_TYPE = Name("ua.para.AlgebraHomBody")
_F_FUNCTOR    = Name("functor")
_F_DIRECTION  = Name("direction")
_F_CELLS      = Name("cells")

# Sub-record type for the lens payload (3 fields, residual optional).
_LENS_TYPE     = Name("ua.para.LensBody")
_F_FORWARD     = Name("forward")
_F_BACKWARD    = Name("backward")
_F_RESIDUAL    = Name("residualSort")


# ---------------------------------------------------------------------------
# Cell — wrapper over a TermInject of the Para 1-cell union
# ---------------------------------------------------------------------------

class Cell(_RecordView):
    """A 1-cell in 2-category Para — a typed algebraic morphism descriptor.

    Cell is unified-algebra's **algebraic IR**, distinct from generic Hydra
    terms. Variants are locked at 9: ``eq``, ``lit``, ``iden``, ``copy``,
    ``delete``, ``seq``, ``par``, ``algebraHom``, ``lens``. No additions, no
    removals — extensions go through the existing surface or stay out.

    Cell carries categorical structure that polymorphic Hydra terms do not
    express directly:

    - Monoidal product (``seq`` / ``par``) with comonoid copy/delete laws.
    - Optic residual threading (``lens``, height-1 and height-2).
    - Recursion schemes (``algebraHom`` for inductive walker, coinductive
      driver, Tarski iterator — Hydra has no fixpoint/μ term).

    The Cell payload is encoded as a Hydra union ``ua.para.Cell``. At compile
    time each variant lowers to one of:

    - A registered Hydra ``Primitive`` via ``prim1`` (atomic eq/lit/iden/
      copy/delete; composed seq/par for Para children).
    - A Python closure stored in ``compiled_fns`` (the fast path; bypasses
      ``reduce_term``).
    - A ``CompiledLens`` dataclass for lens cells (not graph-registered;
      lives in ``compiled_fns`` only because forward/backward are
      JIT-compiled closures, not Hydra terms).

    See ``ARCHITECTURE.md`` § "Hydra ↔ unified-algebra boundary" — Cell is
    **not** to be collapsed into generic Hydra terms.
    """
    __slots__ = ()

    def __init__(self, term):
        if isinstance(term, Cell):
            term = term._term
        self._term = term

    @property
    def kind(self) -> str:
        """Variant tag: ``eq`` | ``lit`` | ``iden`` | ``seq`` | ``par`` | ``copy`` | ``delete`` | ``algebraHom`` | ``lens``."""
        return self._term.value.field.name.value

    @property
    def _payload(self):
        return self._term.value.field.term

    def _expect(self, *kinds: str) -> None:
        if self.kind not in kinds:
            raise AttributeError(
                f"Cell accessor not valid for kind={self.kind!r} "
                f"(expected one of {kinds})"
            )

    @property
    def equation_name(self) -> str:
        self._expect("eq")
        return _literal_value(self._payload)

    @property
    def value_term(self):
        self._expect("lit")
        return self._payload

    @property
    def left(self) -> "Cell":
        self._expect("seq", "par")
        return Cell(self._payload.value[0])

    @property
    def right(self) -> "Cell":
        self._expect("seq", "par")
        return Cell(self._payload.value[1])

    @property
    def sort(self) -> Sort | ProductSort:
        self._expect("copy", "delete", "iden")
        return sort_wrap(self._payload)

    @property
    def functor(self) -> Functor:
        self._expect("algebraHom")
        return Functor.from_term(_record_field(self._payload, "functor"))

    @property
    def direction(self) -> str:
        self._expect("algebraHom")
        return _literal_value(_record_field(self._payload, "direction"))

    @property
    def cells(self) -> list["Cell"]:
        self._expect("algebraHom")
        list_term = _record_field(self._payload, "cells")
        return [Cell(t) for t in list_term.value]

    @property
    def forward(self) -> "Cell":
        self._expect("lens")
        return Cell(_record_field(self._payload, "forward"))

    @property
    def backward(self) -> "Cell":
        self._expect("lens")
        return Cell(_record_field(self._payload, "backward"))

    @property
    def residual_sort(self) -> Sort | ProductSort | None:
        self._expect("lens")
        import hydra.core as core
        t = _record_field(self._payload, "residualSort")
        if isinstance(t, core.TermUnit):
            return None
        return sort_wrap(t)

    def __eq__(self, other) -> bool:
        return isinstance(other, Cell) and self._term == other._term

    def __hash__(self) -> int:
        return hash(self._term)

    def __repr__(self) -> str:
        return f"Cell({pretty(self)})"


def _record_field(record_term, name: str):
    for f in record_term.value.fields:
        if f.name.value == name:
            return f.term
    raise KeyError(f"Record has no field {name!r}")


# ---------------------------------------------------------------------------
# Constructors
# ---------------------------------------------------------------------------

def eq(name: str) -> Cell:
    """Atomic 1-cell: reference to a declared Equation by name."""
    return Cell(Terms.inject(CELL_TYPE_NAME, _K_EQ, Terms.string(name)))


def lit(value_term) -> Cell:
    """0-ary constant 1-cell: ``1 → A``. ``value_term`` is a Hydra term."""
    return Cell(Terms.inject(CELL_TYPE_NAME, _K_LIT, value_term))


def seq(f: Cell, g: Cell) -> Cell:
    """Sequential composition: ``f ; g``."""
    payload = Terms.pair(_RecordView._unwrap(f), _RecordView._unwrap(g))
    return Cell(Terms.inject(CELL_TYPE_NAME, _K_SEQ, payload))


def par(f: Cell, g: Cell) -> Cell:
    """Monoidal product: ``f ⊗ g``."""
    payload = Terms.pair(_RecordView._unwrap(f), _RecordView._unwrap(g))
    return Cell(Terms.inject(CELL_TYPE_NAME, _K_PAR, payload))


def copy(sort: Sort | ProductSort) -> Cell:
    """Comonoid copy: ``Δ_A : A → A × A``."""
    return Cell(Terms.inject(CELL_TYPE_NAME, _K_COPY, _RecordView._unwrap(sort)))


def delete(sort: Sort | ProductSort) -> Cell:
    """Comonoid delete: ``!_A : A → 1``."""
    return Cell(Terms.inject(CELL_TYPE_NAME, _K_DELETE, _RecordView._unwrap(sort)))


def iden(sort: Sort | ProductSort) -> Cell:
    """Identity 1-cell: ``id_A : A → A``. Multiplicative identity of ``;``."""
    return Cell(Terms.inject(CELL_TYPE_NAME, _K_IDEN, _RecordView._unwrap(sort)))


def lens(
    forward: Cell,
    backward: Cell,
    *,
    residual: Sort | ProductSort | None = None,
) -> Cell:
    """Atomic 1-cell in the Optic 2-category.

    Without ``residual``: height-1 lens — ``forward: A→B``, ``backward: B→A``.
    With    ``residual=R``: height-2 optic — ``forward: A→R×B``, ``backward: R×B'→A'``.
    """
    res_term = _RecordView._unwrap(residual) if residual is not None else Terms.unit()
    payload = Terms.record(_LENS_TYPE, [
        Field(_F_FORWARD,  _RecordView._unwrap(forward)),
        Field(_F_BACKWARD, _RecordView._unwrap(backward)),
        Field(_F_RESIDUAL, res_term),
    ])
    return Cell(Terms.inject(CELL_TYPE_NAME, _K_LENS, payload))


def algebra_hom(functor: Functor, direction: str, cells: list[Cell]) -> Cell:
    """Induced unique (co)algebra hom over a polynomial Functor.

    ``direction``:
        ``"algebra"``   — inductive walker: unique morphism from initial F-algebra.
        ``"coalgebra"`` — coinductive walker: morphism to terminal F-coalgebra.
    ``cells``: one Cell per summand of ``functor.summands()``, in order.
    For a ``One`` summand, use ``lit(<value_term>)``.
    """
    if direction not in ("algebra", "coalgebra"):
        raise ValueError(
            f"algebra_hom: direction must be 'algebra' or 'coalgebra', got {direction!r}"
        )
    payload = Terms.record(_ALG_HOM_TYPE, [
        Field(_F_FUNCTOR,   _RecordView._unwrap(functor)),
        Field(_F_DIRECTION, Terms.string(direction)),
        Field(_F_CELLS,     Terms.list_([_RecordView._unwrap(c) for c in cells])),
    ])
    return Cell(Terms.inject(CELL_TYPE_NAME, _K_ALG_HOM, payload))


# ---------------------------------------------------------------------------
# Pretty-printer
# ---------------------------------------------------------------------------

def pretty(cell: Cell) -> str:
    """Render a Cell in a readable surface form."""
    k = cell.kind
    if k == "eq":
        return cell.equation_name
    if k == "lit":
        return "lit(_)"
    if k == "seq":
        return f"({pretty(cell.left)} ; {pretty(cell.right)})"
    if k == "par":
        return f"({pretty(cell.left)} ⊗ {pretty(cell.right)})"
    if k == "copy":
        return f"^[{cell.sort.name}]"
    if k == "delete":
        return f"![{cell.sort.name}]"
    if k == "iden":
        return f"_[{cell.sort.name}]"
    if k == "algebraHom":
        cell_strs = ", ".join(pretty(c) for c in cell.cells)
        return f"hom[{cell.functor.name}, {cell.direction}]({cell_strs})"
    if k == "lens":
        rs = cell.residual_sort
        tag = f"@{rs.name}" if rs is not None else ""
        return f"lens{tag}({pretty(cell.forward)}, {pretty(cell.backward)})"
    raise ValueError(f"unknown Cell kind {k!r}")


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_cell(
    cell: Cell,
    eq_by_name: dict,
    sorts_by_name: dict[str, Sort | ProductSort] | None = None,
) -> None:
    """Walk the Cell tree, check all references resolve.

    - ``eq(name)``           — name must be in ``eq_by_name``
    - ``copy(s)`` / ``delete(s)`` — sort name must be in ``sorts_by_name`` (if provided)
    - ``lens(_, _, residual=R)``  — if R is set, R.name must be in ``sorts_by_name``
    - ``algebra_hom(F, _, cs)`` — F.validate() succeeds; F's const sorts must be in
                                  ``sorts_by_name``; recurse on each cell in ``cs``
    - ``seq`` / ``par``      — recurse on left and right
    - ``lens``               — recurse on forward and backward
    - ``lit``                — no-op (literal has no name references)

    Raises ``ValueError`` on the first failure with a path-tagged message.
    """
    _validate(cell, eq_by_name, sorts_by_name, path=cell.kind)


def _validate(cell: Cell, eq_by_name, sorts_by_name, *, path: str) -> None:
    k = cell.kind
    if k == "eq":
        if cell.equation_name not in eq_by_name:
            raise ValueError(
                f"{path}: eq references unknown equation {cell.equation_name!r}"
            )
        return
    if k == "lit":
        return
    if k in ("seq", "par"):
        _validate(cell.left,  eq_by_name, sorts_by_name, path=f"{path}.left")
        _validate(cell.right, eq_by_name, sorts_by_name, path=f"{path}.right")
        return
    if k in ("copy", "delete", "iden"):
        if sorts_by_name is not None and cell.sort.name not in sorts_by_name:
            raise ValueError(
                f"{path}: {k} references unknown sort {cell.sort.name!r}"
            )
        return
    if k == "lens":
        _validate(cell.forward,  eq_by_name, sorts_by_name, path=f"{path}.fwd")
        _validate(cell.backward, eq_by_name, sorts_by_name, path=f"{path}.bwd")
        rs = cell.residual_sort
        if rs is not None and sorts_by_name is not None and rs.name not in sorts_by_name:
            raise ValueError(
                f"{path}: lens residual references unknown sort {rs.name!r}"
            )
        return
    if k == "algebraHom":
        cell.functor.validate()
        if sorts_by_name is not None:
            unknown = {s.name for s in cell.functor.consts()} - set(sorts_by_name)
            if unknown:
                raise ValueError(
                    f"{path}: functor {cell.functor.name!r} references unknown "
                    f"sorts: {sorted(unknown)}"
                )
        for i, c in enumerate(cell.cells):
            _validate(c, eq_by_name, sorts_by_name, path=f"{path}.cell[{i}]")
        return
    raise ValueError(f"{path}: unknown Cell kind {k!r}")


# ---------------------------------------------------------------------------
# Re-export the runtime so external imports stay stable
# ---------------------------------------------------------------------------

from ._para_runtime import (  # noqa: E402
    CompiledLens, CompiledMorphism, Matcher, compile_cell,
)


__all__ = [
    "Cell", "CELL_TYPE_NAME",
    "eq", "lit", "iden", "seq", "par", "copy", "delete", "lens", "algebra_hom",
    "pretty", "validate_cell",
    "compile_cell", "CompiledLens", "CompiledMorphism", "Matcher",
]
