# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# EXPLORATORY EVIDENCE ONLY — not design authority.
# These are structural probes. They pass arguments in ways that exploit
# Python's duck typing (e.g. CompositionError as a Space), not in ways
# the API is designed to be used. Do not use these to infer behavioral
# contracts; see test_morphism_contracts.py for those.
import pytest
import unialg.morphism as module_0


def test_case_0():
    module_0.CompositionError()


def test_case_1():
    composition_error_0 = module_0.CompositionError()
    morphism_0 = module_0.identity(module_0.plain, composition_error_0)
    module_0.compose(morphism_0, morphism_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    composition_error_0 = module_0.CompositionError()
    morphism_0 = module_0.identity(module_0.plain, composition_error_0)
    morphism_1 = module_0.compose(morphism_0, morphism_0)
    morphism_0.__delattr__(morphism_1)


@pytest.mark.xfail(strict=True)
def test_case_3():
    composition_error_0 = module_0.CompositionError()
    morphism_0 = module_0.identity(module_0.plain, composition_error_0)
    var_0 = morphism_0.__hash__()
    morphism_1 = module_0.identity(module_0.plain, var_0)
    module_0.compose(morphism_0, morphism_1)


def test_case_4():
    none_type_0 = None
    module_0.delete(module_0.plain, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    none_type_0 = None
    morphism_0 = module_0.identity(module_0.plain, none_type_0)
    morphism_1 = module_0.delete(module_0.plain, morphism_0)
    module_0.compose(morphism_1, morphism_1)
