-- GENERATED by explore/gen-catalogue.hs — do not edit by hand.
{-# LANGUAGE OverloadedStrings #-}
module Catalogue (allArchSeeds, seeds) where

import Data.Function (on)
import Data.List (nubBy)
import Seed (SeedEntry(..), seedLabel)
import qualified Moore
import qualified SeqRnn
import qualified StreamRnn
import qualified TreeRnn

allArchSeeds :: [(String, [(String, SeedEntry)])]
allArchSeeds =
  [ ("moore", Moore.backendSeeds)
  , ("seq_rnn", SeqRnn.backendSeeds)
  , ("stream_rnn", StreamRnn.backendSeeds)
  , ("tree_rnn", TreeRnn.backendSeeds)
  ]

seeds :: [SeedEntry]
seeds = nubBy ((==) `on` seedLabel) $ concatMap (map snd . snd) allArchSeeds
