# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# EXPLORATORY EVIDENCE ONLY — not design authority.
import pytest
import unialg.typing as module_0


def test_case_0():
    str_0 = 'q-o|Kj+|y{om<."'
    space_0 = module_0.Space(str_0)
    space_0.__repr__()


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    product_space_0 = module_0.ProductSpace(none_type_0, none_type_0)
    assert (
        f"{type(module_0.ProductSpace.name).__module__}.{type(module_0.ProductSpace.name).__qualname__}"
        == "builtins.property"
    )
    product_space_0.__repr__()


@pytest.mark.xfail(strict=True)
def test_case_2():
    unit_space_0 = module_0.UnitSpace()
    assert (
        f"{type(module_0.UnitSpace.name).__module__}.{type(module_0.UnitSpace.name).__qualname__}"
        == "builtins.property"
    )
    none_type_0 = None
    str_0 = unit_space_0.__repr__()
    assert str_0 == "1"
    space_0 = module_0.Space(none_type_0)
    product_space_0 = module_0.ProductSpace(space_0, none_type_0)
    assert (
        f"{type(module_0.ProductSpace.name).__module__}.{type(module_0.ProductSpace.name).__qualname__}"
        == "builtins.property"
    )
    product_space_0.__delattr__(product_space_0)


def test_case_3():
    unit_space_0 = module_0.UnitSpace()
    assert (
        f"{type(module_0.UnitSpace.name).__module__}.{type(module_0.UnitSpace.name).__qualname__}"
        == "builtins.property"
    )
    product_space_0 = module_0.ProductSpace(unit_space_0, unit_space_0)
    assert (
        f"{type(module_0.ProductSpace.name).__module__}.{type(module_0.ProductSpace.name).__qualname__}"
        == "builtins.property"
    )
    str_0 = product_space_0.__repr__()
    assert str_0 == "1 × 1"
    str_1 = unit_space_0.__repr__()
    assert str_1 == "1"
