# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# EXPLORATORY EVIDENCE ONLY — not design authority.
# Coverage of ParaMorphism, para_compose, and embed is limited because
# these require properly constructed Hydra terms. See test_para_contracts.py
# (when written) for behavioral contracts.
import pytest
import enum as module_0
import hydra.dsl.terms as module_1
import unialg.morphism.ops as module_2


@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0.global_str()


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    term_0 = module_1.int16(bool_0)
    module_2.embed(term_0)
