-- Regenerate explore/support/haskell/Catalogue.hs from the explore/archs/ directories.
--
-- Run from the haskell/ project root:
--   runghc explore/gen-catalogue.hs
--
-- Required when adding a new architecture directory under explore/archs/.

import Control.Monad (filterM)
import Data.Char (isLower, toUpper)
import Data.List (intercalate, sort)
import System.Directory (doesDirectoryExist, listDirectory)
import System.FilePath ((</>))

main :: IO ()
main = do
  let archsDir = "explore" </> "archs"
  entries  <- listDirectory archsDir
  archDirs <- fmap sort . filterM (doesDirectoryExist . (archsDir </>)) $
                filter startsLower entries
  let pairs   = zip archDirs (map toPascalCase archDirs)
      outPath = "explore" </> "support" </> "haskell" </> "Catalogue.hs"
  writeFile outPath (renderCatalogue pairs)
  putStrLn $ "wrote " ++ outPath ++ " (" ++ show (length pairs) ++ " archs)"

startsLower :: String -> Bool
startsLower []    = False
startsLower (c:_) = isLower c

toPascalCase :: String -> String
toPascalCase = concatMap capitalise . splitOn '_'
  where
    capitalise []     = []
    capitalise (c:cs) = toUpper c : cs
    splitOn _ [] = []
    splitOn sep s = case break (== sep) s of
      (w, [])     -> [w]
      (w, _:rest) -> w : splitOn sep rest

renderCatalogue :: [(String, String)] -> String
renderCatalogue pairs = unlines $
  [ "-- GENERATED by explore/gen-catalogue.hs — do not edit by hand."
  , "{-# LANGUAGE OverloadedStrings #-}"
  , "module Catalogue (allArchSeeds, seeds) where"
  , ""
  , "import Data.Function (on)"
  , "import Data.List (nubBy)"
  , "import Seed (SeedEntry(..), seedLabel)"
  ]
  ++ map (\(_, m) -> "import qualified " ++ m) pairs ++
  [ ""
  , "allArchSeeds :: [(String, [(String, SeedEntry)])]"
  , "allArchSeeds ="
  , "  [ " ++ intercalate "\n  , " (map entry pairs)
  , "  ]"
  , ""
  , "seeds :: [SeedEntry]"
  , "seeds = nubBy ((==) `on` seedLabel) $ concatMap (map snd . snd) allArchSeeds"
  ]
  where
    entry (d, m) = "(\"" ++ d ++ "\", " ++ m ++ ".backendSeeds)"
